### ISSUE TITLE
Not able to use the sentiwordnet

### ISSUE THREAD

**Issue by bubunia2000** [nicbet/sentiment-analysis-java#1]
Hi,

I tried to create the file for testing the sentiwordnet for one of my input file(amazon review). But when i ran the code in eclipse it is throwing error. I am using jdk1.8. Input file is as attached.
[yelp_labelled.txt](https://github.com/kuyio/sentiment-analysis-java/files/7784080/yelp_labelled.txt)

java.io.FileNotFoundException: res_swn.txt (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at edu.stanford.nlp.sobhan.sentiwordnetimpl.<init>(sentiwordnetimpl.java:22)
	at edu.stanford.nlp.sobhan.sentiwordnetimpl.main(sentiwordnetimpl.java:134)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at edu.stanford.nlp.sobhan.sentiwordnetimpl.main(sentiwordnetimpl.java:135)

**Comment by nicbet** [comment]
Hi @bubunia2000, looks like a path problem. The file is included with the project at the `res/swn.txt` path, your error states it cannot find `res_swn.txt`.

**Comment by nicbet** [comment]
Closing in preparation for archive
